services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: 8pods-postgres-dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: 8pods_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API (Development)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: 8pods-backend-dev
    environment:
      NODE_ENV: development
      PORT: 3000
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: 8pods_db
      RATE_LIMIT_TTL: 60
      RATE_LIMIT_MAX: 100
      ITUNES_API_BASE_URL: https://itunes.apple.com
      CORS_ORIGIN: "*"
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend/src:/app/src
      - ./backend/package.json:/app/package.json
      - ./backend/package-lock.json:/app/package-lock.json
      - ./backend/tsconfig.json:/app/tsconfig.json
      - ./backend/tsconfig.build.json:/app/tsconfig.build.json
      - ./backend/nest-cli.json:/app/nest-cli.json
      - /app/node_modules

  # Frontend Application (Development)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: 8pods-frontend-dev
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3000/api/v1
      NODE_ENV: development
    ports:
      - "3001:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/package.json:/app/package.json
      - ./frontend/package-lock.json:/app/package-lock.json
      - ./frontend/next.config.ts:/app/next.config.ts
      - ./frontend/tsconfig.json:/app/tsconfig.json
      - ./frontend/postcss.config.mjs:/app/postcss.config.mjs
      - ./frontend/tailwind.config.ts:/app/tailwind.config.ts
      - /app/node_modules
      - /app/.next

volumes:
  postgres_data_dev:
